language: python

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1

before_install:
  - mkdir -p buildout-cache/{eggs,downloads}

install:
  - virtualenv .
  - bin/pip install --upgrade pip
  - bin/pip install -r requirements.txt
  - sed -ie "s#plone-4.3#plone-$PLONE_VERSION#" buildout.cfg
  - sed -ie "s#travis-4.3#travis-$PLONE_VERSION#" travis.cfg
  - bin/buildout -Nc travis.cfg

script:
  - bin/test

after_success:
  - bin/coverage run bin/test
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
