language: python

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

before_install:
  - mkdir -p buildout-cache/{eggs,downloads}

install:
  - virtualenv .
  - bin/pip install --upgrade pip
  - bin/pip install -r requirements.txt
  - bin/buildout -Nc travis.cfg

script:
  - bin/test

after_success:
  - bin/coverage run bin/test
  - pip install coveralls==0.5
  - coveralls

notifications:
  email:
    - devs@imio.be
